[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wissol = "64drnnxTSEe9fpeTEQ3MeVtm1Vztzf7bR4Cigs9X7S5j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
